### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by suterma** [jsakamoto/CSharpMethodsCodeSnippets#1]
Hey, nice idea. What about a test snippet for example for NUnit like
[Test]
public void Test.....(){}

**Comment by jsakamoto** [comment]
Thank you for your nice suggestion ! :smile:

But, sorry I'm not NUnit user, I'm xUnit.net user...

[xUnit Code Snippets - Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/032cd260-d4cd-4849-adff-648ea9a28265)

Therefore, I have no plan to support code snippets for NUnit test method at this time.
Could you accept this situation?

**Comment by suterma** [comment]
Hi jsakamoto,

of course I can, it's no problem.

I am developing a Visual Studio Extension myself, if you want you may 
look at it: 
https://visualstudiogallery.msdn.microsoft.com/5d17a777-0964-47e3-a6e5-3eed5b31ea93

Have fun,

Marcel

**Comment by jsakamoto** [comment]
Thank you for your reply.

Oh, it's nice extension.

[Copy for review](https://twitter.com/jsakamoto/status/578340265976434688)

I have no skill to building Visual Studio extension... you are great.

Happy coding :)
