### ISSUE TITLE
Request : new method snippets

### ISSUE THREAD

**Issue by hamjo** [jsakamoto/CSharpMethodsCodeSnippets#2]
Hi, 

Could you add snippets for methods receiving event callbacks?
Like this : 
`public void MyMethod(object sender, EventArgs args)`

Also, would it be possible to add snippets for methods with one, two or three parameters like this (or so) :
`methone`, `methtwo`

(if it's not the appropriate place to make those requests, please let me know)

Jo Ham

**Comment by jsakamoto** [comment]
Thank you for your proposal.

I'll consider those ideas, and it will be  implemented at last. 

But I'm busy in these days, so please let me few days or weeks.

**Comment by hamjo** [comment]
Thank you for the answer.
Any delay is fine, I just wanted the idea to get to you.

Jo Ham

**Comment by jsakamoto** [comment]
@wertwert129 

> Could you add snippets for methods receiving event callbacks?

I tried to append new code snippets into this project.

You can get pre-release .vsix package file from here: [Experimental - Add "event handler" code snippets](https://github.com/jsakamoto/CSharpMethodsCodeSnippets/releases/tag/experimental%2Fevent-handler)

Does this matched what you want?

P.S.  
I'll continue to append new snippets for method which has some arguments.

**Comment by hamjo** [comment]
Exactly what I wanted!

Thank you very much for the addition!

**Comment by jsakamoto** [comment]
@wertwert129 

Thank you for your rapid reply.

And, I tried to append new code snippets those are "method" with some arguments into this project.

You can get pre-release .vsix package file from here: [Experimental - Add "method" code snippets with some arguments](https://github.com/jsakamoto/CSharpMethodsCodeSnippets/releases)

Does this matched what you want, too?

If it is good, then I'll append snippets that static method version and extension method version.

**Comment by hamjo** [comment]
All good! Also like I imagined it!

**Comment by jsakamoto** [comment]
@wertwert129 Thanks. 

I'll finish this work in few days, and I'll publish to Visual Studio Marketplace officially.

**Comment by jsakamoto** [comment]
I finished my home work :)

https://marketplace.visualstudio.com/items?itemName=jsakamoto.CMethodsCodeSnippets
